export type Country = {
  iso2: string
  name: string
  dial_code: string
}

export function flagFromIso2(iso2: string): string {
  if (!iso2 || iso2.length !== 2) return ''
  return iso2
    .toUpperCase()
    .replace(/./g, (c) => String.fromCodePoint(127397 + c.charCodeAt(0)))
}

// Curated, alphabetical list of widely used countries.
// Add/edit as needed; iso2 is used to derive the flag emoji.
export const COUNTRIES: Country[] = [
  { iso2: 'AF', name: 'Afghanistan', dial_code: '+93' },
  { iso2: 'AL', name: 'Albania', dial_code: '+355' },
  { iso2: 'DZ', name: 'Algeria', dial_code: '+213' },
  { iso2: 'AR', name: 'Argentina', dial_code: '+54' },
  { iso2: 'AM', name: 'Armenia', dial_code: '+374' },
  { iso2: 'AU', name: 'Australia', dial_code: '+61' },
  { iso2: 'AT', name: 'Austria', dial_code: '+43' },
  { iso2: 'AZ', name: 'Azerbaijan', dial_code: '+994' },
  { iso2: 'BH', name: 'Bahrain', dial_code: '+973' },
  { iso2: 'BD', name: 'Bangladesh', dial_code: '+880' },
  { iso2: 'BY', name: 'Belarus', dial_code: '+375' },
  { iso2: 'BE', name: 'Belgium', dial_code: '+32' },
  { iso2: 'BO', name: 'Bolivia', dial_code: '+591' },
  { iso2: 'BA', name: 'Bosnia and Herzegovina', dial_code: '+387' },
  { iso2: 'BR', name: 'Brazil', dial_code: '+55' },
  { iso2: 'BG', name: 'Bulgaria', dial_code: '+359' },
  { iso2: 'KH', name: 'Cambodia', dial_code: '+855' },
  { iso2: 'CM', name: 'Cameroon', dial_code: '+237' },
  { iso2: 'CA', name: 'Canada', dial_code: '+1' },
  { iso2: 'CL', name: 'Chile', dial_code: '+56' },
  { iso2: 'CN', name: 'China', dial_code: '+86' },
  { iso2: 'CO', name: 'Colombia', dial_code: '+57' },
  { iso2: 'CR', name: 'Costa Rica', dial_code: '+506' },
  { iso2: 'HR', name: 'Croatia', dial_code: '+385' },
  { iso2: 'CU', name: 'Cuba', dial_code: '+53' },
  { iso2: 'CY', name: 'Cyprus', dial_code: '+357' },
  { iso2: 'CZ', name: 'Czechia', dial_code: '+420' },
  { iso2: 'DK', name: 'Denmark', dial_code: '+45' },
  { iso2: 'DO', name: 'Dominican Republic', dial_code: '+1' },
  { iso2: 'EC', name: 'Ecuador', dial_code: '+593' },
  { iso2: 'EG', name: 'Egypt', dial_code: '+20' },
  { iso2: 'EE', name: 'Estonia', dial_code: '+372' },
  { iso2: 'ET', name: 'Ethiopia', dial_code: '+251' },
  { iso2: 'FI', name: 'Finland', dial_code: '+358' },
  { iso2: 'FR', name: 'France', dial_code: '+33' },
  { iso2: 'GE', name: 'Georgia', dial_code: '+995' },
  { iso2: 'DE', name: 'Germany', dial_code: '+49' },
  { iso2: 'GH', name: 'Ghana', dial_code: '+233' },
  { iso2: 'GR', name: 'Greece', dial_code: '+30' },
  { iso2: 'GT', name: 'Guatemala', dial_code: '+502' },
  { iso2: 'HK', name: 'Hong Kong', dial_code: '+852' },
  { iso2: 'HU', name: 'Hungary', dial_code: '+36' },
  { iso2: 'IS', name: 'Iceland', dial_code: '+354' },
  { iso2: 'IN', name: 'India', dial_code: '+91' },
  { iso2: 'ID', name: 'Indonesia', dial_code: '+62' },
  { iso2: 'IR', name: 'Iran', dial_code: '+98' },
  { iso2: 'IQ', name: 'Iraq', dial_code: '+964' },
  { iso2: 'IE', name: 'Ireland', dial_code: '+353' },
  { iso2: 'IL', name: 'Israel', dial_code: '+972' },
  { iso2: 'IT', name: 'Italy', dial_code: '+39' },
  { iso2: 'JM', name: 'Jamaica', dial_code: '+1' },
  { iso2: 'JP', name: 'Japan', dial_code: '+81' },
  { iso2: 'JO', name: 'Jordan', dial_code: '+962' },
  { iso2: 'KZ', name: 'Kazakhstan', dial_code: '+7' },
  { iso2: 'KE', name: 'Kenya', dial_code: '+254' },
  { iso2: 'KR', name: 'South Korea', dial_code: '+82' },
  { iso2: 'KW', name: 'Kuwait', dial_code: '+965' },
  { iso2: 'KG', name: 'Kyrgyzstan', dial_code: '+996' },
  { iso2: 'LA', name: 'Laos', dial_code: '+856' },
  { iso2: 'LV', name: 'Latvia', dial_code: '+371' },
  { iso2: 'LB', name: 'Lebanon', dial_code: '+961' },
  { iso2: 'LY', name: 'Libya', dial_code: '+218' },
  { iso2: 'LT', name: 'Lithuania', dial_code: '+370' },
  { iso2: 'LU', name: 'Luxembourg', dial_code: '+352' },
  { iso2: 'MO', name: 'Macau', dial_code: '+853' },
  { iso2: 'MY', name: 'Malaysia', dial_code: '+60' },
  { iso2: 'MV', name: 'Maldives', dial_code: '+960' },
  { iso2: 'MT', name: 'Malta', dial_code: '+356' },
  { iso2: 'MX', name: 'Mexico', dial_code: '+52' },
  { iso2: 'MD', name: 'Moldova', dial_code: '+373' },
  { iso2: 'MN', name: 'Mongolia', dial_code: '+976' },
  { iso2: 'ME', name: 'Montenegro', dial_code: '+382' },
  { iso2: 'MA', name: 'Morocco', dial_code: '+212' },
  { iso2: 'MM', name: 'Myanmar', dial_code: '+95' },
  { iso2: 'NP', name: 'Nepal', dial_code: '+977' },
  { iso2: 'NL', name: 'Netherlands', dial_code: '+31' },
  { iso2: 'NZ', name: 'New Zealand', dial_code: '+64' },
  { iso2: 'NG', name: 'Nigeria', dial_code: '+234' },
  { iso2: 'NO', name: 'Norway', dial_code: '+47' },
  { iso2: 'OM', name: 'Oman', dial_code: '+968' },
  { iso2: 'PK', name: 'Pakistan', dial_code: '+92' },
  { iso2: 'PS', name: 'Palestine', dial_code: '+970' },
  { iso2: 'PA', name: 'Panama', dial_code: '+507' },
  { iso2: 'PY', name: 'Paraguay', dial_code: '+595' },
  { iso2: 'PE', name: 'Peru', dial_code: '+51' },
  { iso2: 'PH', name: 'Philippines', dial_code: '+63' },
  { iso2: 'PL', name: 'Poland', dial_code: '+48' },
  { iso2: 'PT', name: 'Portugal', dial_code: '+351' },
  { iso2: 'QA', name: 'Qatar', dial_code: '+974' },
  { iso2: 'RO', name: 'Romania', dial_code: '+40' },
  { iso2: 'RU', name: 'Russia', dial_code: '+7' },
  { iso2: 'SA', name: 'Saudi Arabia', dial_code: '+966' },
  { iso2: 'RS', name: 'Serbia', dial_code: '+381' },
  { iso2: 'SG', name: 'Singapore', dial_code: '+65' },
  { iso2: 'SK', name: 'Slovakia', dial_code: '+421' },
  { iso2: 'SI', name: 'Slovenia', dial_code: '+386' },
  { iso2: 'ZA', name: 'South Africa', dial_code: '+27' },
  { iso2: 'ES', name: 'Spain', dial_code: '+34' },
  { iso2: 'LK', name: 'Sri Lanka', dial_code: '+94' },
  { iso2: 'SE', name: 'Sweden', dial_code: '+46' },
  { iso2: 'CH', name: 'Switzerland', dial_code: '+41' },
  { iso2: 'SY', name: 'Syria', dial_code: '+963' },
  { iso2: 'TW', name: 'Taiwan', dial_code: '+886' },
  { iso2: 'TJ', name: 'Tajikistan', dial_code: '+992' },
  { iso2: 'TZ', name: 'Tanzania', dial_code: '+255' },
  { iso2: 'TH', name: 'Thailand', dial_code: '+66' },
  { iso2: 'TN', name: 'Tunisia', dial_code: '+216' },
  { iso2: 'TR', name: 'Turkey', dial_code: '+90' },
  { iso2: 'TM', name: 'Turkmenistan', dial_code: '+993' },
  { iso2: 'UG', name: 'Uganda', dial_code: '+256' },
  { iso2: 'UA', name: 'Ukraine', dial_code: '+380' },
  { iso2: 'AE', name: 'United Arab Emirates', dial_code: '+971' },
  { iso2: 'GB', name: 'United Kingdom', dial_code: '+44' },
  { iso2: 'US', name: 'United States', dial_code: '+1' },
  { iso2: 'UY', name: 'Uruguay', dial_code: '+598' },
  { iso2: 'UZ', name: 'Uzbekistan', dial_code: '+998' },
  { iso2: 'VE', name: 'Venezuela', dial_code: '+58' },
  { iso2: 'VN', name: 'Vietnam', dial_code: '+84' },
  { iso2: 'YE', name: 'Yemen', dial_code: '+967' },
  { iso2: 'ZM', name: 'Zambia', dial_code: '+260' },
  { iso2: 'ZW', name: 'Zimbabwe', dial_code: '+263' },
]

export const DEFAULT_COUNTRY_ISO2 = 'US'

export function findCountryByIso2(iso2: string): Country | undefined {
  return COUNTRIES.find((c) => c.iso2 === iso2.toUpperCase())
}
